name: scrape

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:

  scrape:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sc') }}

    - uses: olafurpg/setup-scala@v7
      with:
        java-version: openjdk@1.14

    - name: Install Firefox
      run: sudo apt update && sudo apt install firefox firefox-geckodriver

    - name: Scrape
      run: ./mill scraper.run --searchPath /koop/hoofddorp/0-400000/bouwperiode-2001-2010/bouwperiode-na-2010/

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_message: Scraped


